version: '3.8'

services:
  express-app:
    build: .
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["/bin/sh", "-c", "mkdir -p /data/nginx/cache && exec nginx -g 'daemon off;'"]
