version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - .:/app 

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
